export enum LandingPageSetionsNameEnum {
    HOME = "HOME",
    OVERVIEW = "OVERVIEW",
    ABOUTITINERARY = "ABOUTITINERARY",
    OURPRICING = "OURPRICING",
    INCLUSIONS = "INCLUSIONS",
    EXCLUSIONS = "EXCLUSIONS",
} 